/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'albert' at '24/04/17 10:31' with Gradle 2.6
 *
 * @author albert, @date 24/04/17 10:31
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
